// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
GrabFood

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.1.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package grabfood

import (
	"encoding/json"
)

// checks if the GenerateSTOQRCodeResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GenerateSTOQRCodeResponse{}

// GenerateSTOQRCodeResponse The STO QR deeplink response
type GenerateSTOQRCodeResponse struct {
	// The deeplink of scan to order QR.
	QrCode *string `json:"qrCode,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GenerateSTOQRCodeResponse GenerateSTOQRCodeResponse

// NewGenerateSTOQRCodeResponse instantiates a new GenerateSTOQRCodeResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGenerateSTOQRCodeResponse() *GenerateSTOQRCodeResponse {
	this := GenerateSTOQRCodeResponse{}
	return &this
}

// NewGenerateSTOQRCodeResponseWithDefaults instantiates a new GenerateSTOQRCodeResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGenerateSTOQRCodeResponseWithDefaults() *GenerateSTOQRCodeResponse {
	this := GenerateSTOQRCodeResponse{}
	return &this
}

// GetQrCode returns the QrCode field value if set, zero value otherwise.
func (o *GenerateSTOQRCodeResponse) GetQrCode() string {
	if o == nil || IsNil(o.QrCode) {
		var ret string
		return ret
	}
	return *o.QrCode
}

// GetQrCodeOk returns a tuple with the QrCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GenerateSTOQRCodeResponse) GetQrCodeOk() (*string, bool) {
	if o == nil || IsNil(o.QrCode) {
		return nil, false
	}
	return o.QrCode, true
}

// HasQrCode returns a boolean if a field has been set.
func (o *GenerateSTOQRCodeResponse) HasQrCode() bool {
	if o != nil && !IsNil(o.QrCode) {
		return true
	}

	return false
}

// SetQrCode gets a reference to the given string and assigns it to the QrCode field.
func (o *GenerateSTOQRCodeResponse) SetQrCode(v string) {
	o.QrCode = &v
}

func (o GenerateSTOQRCodeResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GenerateSTOQRCodeResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.QrCode) {
		toSerialize["qrCode"] = o.QrCode
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GenerateSTOQRCodeResponse) UnmarshalJSON(data []byte) (err error) {
	varGenerateSTOQRCodeResponse := _GenerateSTOQRCodeResponse{}

	err = json.Unmarshal(data, &varGenerateSTOQRCodeResponse)

	if err != nil {
		return err
	}

	*o = GenerateSTOQRCodeResponse(varGenerateSTOQRCodeResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "qrCode")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGenerateSTOQRCodeResponse struct {
	value *GenerateSTOQRCodeResponse
	isSet bool
}

func (v NullableGenerateSTOQRCodeResponse) Get() *GenerateSTOQRCodeResponse {
	return v.value
}

func (v *NullableGenerateSTOQRCodeResponse) Set(val *GenerateSTOQRCodeResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGenerateSTOQRCodeResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGenerateSTOQRCodeResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGenerateSTOQRCodeResponse(val *GenerateSTOQRCodeResponse) *NullableGenerateSTOQRCodeResponse {
	return &NullableGenerateSTOQRCodeResponse{value: val, isSet: true}
}

func (v NullableGenerateSTOQRCodeResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGenerateSTOQRCodeResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


