// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
GrabFood

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.1.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package grabfood

import (
	"encoding/json"
)

// checks if the MenuSyncFailItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MenuSyncFailItem{}

// MenuSyncFailItem struct for MenuSyncFailItem
type MenuSyncFailItem struct {
	// The item's ID in the partner system. 
	Id *string `json:"id,omitempty"`
	// An array of strings of error message.
	Errors []string `json:"errors,omitempty"`
	ModifierGroups []MenuSyncFailModifierGroup `json:"modifierGroups,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _MenuSyncFailItem MenuSyncFailItem

// NewMenuSyncFailItem instantiates a new MenuSyncFailItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMenuSyncFailItem() *MenuSyncFailItem {
	this := MenuSyncFailItem{}
	return &this
}

// NewMenuSyncFailItemWithDefaults instantiates a new MenuSyncFailItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMenuSyncFailItemWithDefaults() *MenuSyncFailItem {
	this := MenuSyncFailItem{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *MenuSyncFailItem) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MenuSyncFailItem) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *MenuSyncFailItem) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *MenuSyncFailItem) SetId(v string) {
	o.Id = &v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *MenuSyncFailItem) GetErrors() []string {
	if o == nil || IsNil(o.Errors) {
		var ret []string
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MenuSyncFailItem) GetErrorsOk() ([]string, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *MenuSyncFailItem) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []string and assigns it to the Errors field.
func (o *MenuSyncFailItem) SetErrors(v []string) {
	o.Errors = v
}

// GetModifierGroups returns the ModifierGroups field value if set, zero value otherwise.
func (o *MenuSyncFailItem) GetModifierGroups() []MenuSyncFailModifierGroup {
	if o == nil || IsNil(o.ModifierGroups) {
		var ret []MenuSyncFailModifierGroup
		return ret
	}
	return o.ModifierGroups
}

// GetModifierGroupsOk returns a tuple with the ModifierGroups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MenuSyncFailItem) GetModifierGroupsOk() ([]MenuSyncFailModifierGroup, bool) {
	if o == nil || IsNil(o.ModifierGroups) {
		return nil, false
	}
	return o.ModifierGroups, true
}

// HasModifierGroups returns a boolean if a field has been set.
func (o *MenuSyncFailItem) HasModifierGroups() bool {
	if o != nil && !IsNil(o.ModifierGroups) {
		return true
	}

	return false
}

// SetModifierGroups gets a reference to the given []MenuSyncFailModifierGroup and assigns it to the ModifierGroups field.
func (o *MenuSyncFailItem) SetModifierGroups(v []MenuSyncFailModifierGroup) {
	o.ModifierGroups = v
}

func (o MenuSyncFailItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MenuSyncFailItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	if !IsNil(o.ModifierGroups) {
		toSerialize["modifierGroups"] = o.ModifierGroups
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MenuSyncFailItem) UnmarshalJSON(data []byte) (err error) {
	varMenuSyncFailItem := _MenuSyncFailItem{}

	err = json.Unmarshal(data, &varMenuSyncFailItem)

	if err != nil {
		return err
	}

	*o = MenuSyncFailItem(varMenuSyncFailItem)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "errors")
		delete(additionalProperties, "modifierGroups")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMenuSyncFailItem struct {
	value *MenuSyncFailItem
	isSet bool
}

func (v NullableMenuSyncFailItem) Get() *MenuSyncFailItem {
	return v.value
}

func (v *NullableMenuSyncFailItem) Set(val *MenuSyncFailItem) {
	v.value = val
	v.isSet = true
}

func (v NullableMenuSyncFailItem) IsSet() bool {
	return v.isSet
}

func (v *NullableMenuSyncFailItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMenuSyncFailItem(val *MenuSyncFailItem) *NullableMenuSyncFailItem {
	return &NullableMenuSyncFailItem{value: val, isSet: true}
}

func (v NullableMenuSyncFailItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMenuSyncFailItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


