// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
GrabFood

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.1.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package grabfood

import (
	"encoding/json"
)

// checks if the EditOrderItemModifier type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EditOrderItemModifier{}

// EditOrderItemModifier struct for EditOrderItemModifier
type EditOrderItemModifier struct {
	// The modifier's external ID in partner system.
	Id *string `json:"id,omitempty"`
	// The modifier's quantity. 0 to remove the modifier, 1 to add or keep the modifier.
	Quantity *int32 `json:"quantity,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _EditOrderItemModifier EditOrderItemModifier

// NewEditOrderItemModifier instantiates a new EditOrderItemModifier object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEditOrderItemModifier() *EditOrderItemModifier {
	this := EditOrderItemModifier{}
	return &this
}

// NewEditOrderItemModifierWithDefaults instantiates a new EditOrderItemModifier object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEditOrderItemModifierWithDefaults() *EditOrderItemModifier {
	this := EditOrderItemModifier{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *EditOrderItemModifier) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditOrderItemModifier) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *EditOrderItemModifier) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *EditOrderItemModifier) SetId(v string) {
	o.Id = &v
}

// GetQuantity returns the Quantity field value if set, zero value otherwise.
func (o *EditOrderItemModifier) GetQuantity() int32 {
	if o == nil || IsNil(o.Quantity) {
		var ret int32
		return ret
	}
	return *o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditOrderItemModifier) GetQuantityOk() (*int32, bool) {
	if o == nil || IsNil(o.Quantity) {
		return nil, false
	}
	return o.Quantity, true
}

// HasQuantity returns a boolean if a field has been set.
func (o *EditOrderItemModifier) HasQuantity() bool {
	if o != nil && !IsNil(o.Quantity) {
		return true
	}

	return false
}

// SetQuantity gets a reference to the given int32 and assigns it to the Quantity field.
func (o *EditOrderItemModifier) SetQuantity(v int32) {
	o.Quantity = &v
}

func (o EditOrderItemModifier) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EditOrderItemModifier) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Quantity) {
		toSerialize["quantity"] = o.Quantity
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *EditOrderItemModifier) UnmarshalJSON(data []byte) (err error) {
	varEditOrderItemModifier := _EditOrderItemModifier{}

	err = json.Unmarshal(data, &varEditOrderItemModifier)

	if err != nil {
		return err
	}

	*o = EditOrderItemModifier(varEditOrderItemModifier)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "quantity")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableEditOrderItemModifier struct {
	value *EditOrderItemModifier
	isSet bool
}

func (v NullableEditOrderItemModifier) Get() *EditOrderItemModifier {
	return v.value
}

func (v *NullableEditOrderItemModifier) Set(val *EditOrderItemModifier) {
	v.value = val
	v.isSet = true
}

func (v NullableEditOrderItemModifier) IsSet() bool {
	return v.isSet
}

func (v *NullableEditOrderItemModifier) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEditOrderItemModifier(val *EditOrderItemModifier) *NullableEditOrderItemModifier {
	return &NullableEditOrderItemModifier{value: val, isSet: true}
}

func (v NullableEditOrderItemModifier) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEditOrderItemModifier) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


