// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
GrabFood

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.1.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package grabfood

import (
	"encoding/json"
)

// checks if the MerchantEarning type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MerchantEarning{}

// MerchantEarning A JSON object reflects the real money the merchant receives. Only applicable for Dine out STO case. `null` if not applicable. Only present in submitOrder webhook. Not present in [ListOrder](#tag/list-order/operation/list-orders) response.
type MerchantEarning struct {
	// The revenue of merchant should receive. revenue = price.eaterpayment - mexfunddiscount
	Revenue *int64 `json:"revenue,omitempty"`
	// The netEarning of merchant should receive. netEarning = revenue - commission
	NetEarning *int64 `json:"netEarning,omitempty"`
	// The mexFundDiscount that user applied from grab app in this payment
	MexFundDiscount *int64 `json:"mexFundDiscount,omitempty"`
	// The commission that grab need charge from this pay merchant transaction.
	Commission *int64 `json:"commission,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _MerchantEarning MerchantEarning

// NewMerchantEarning instantiates a new MerchantEarning object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMerchantEarning() *MerchantEarning {
	this := MerchantEarning{}
	return &this
}

// NewMerchantEarningWithDefaults instantiates a new MerchantEarning object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMerchantEarningWithDefaults() *MerchantEarning {
	this := MerchantEarning{}
	return &this
}

// GetRevenue returns the Revenue field value if set, zero value otherwise.
func (o *MerchantEarning) GetRevenue() int64 {
	if o == nil || IsNil(o.Revenue) {
		var ret int64
		return ret
	}
	return *o.Revenue
}

// GetRevenueOk returns a tuple with the Revenue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MerchantEarning) GetRevenueOk() (*int64, bool) {
	if o == nil || IsNil(o.Revenue) {
		return nil, false
	}
	return o.Revenue, true
}

// HasRevenue returns a boolean if a field has been set.
func (o *MerchantEarning) HasRevenue() bool {
	if o != nil && !IsNil(o.Revenue) {
		return true
	}

	return false
}

// SetRevenue gets a reference to the given int64 and assigns it to the Revenue field.
func (o *MerchantEarning) SetRevenue(v int64) {
	o.Revenue = &v
}

// GetNetEarning returns the NetEarning field value if set, zero value otherwise.
func (o *MerchantEarning) GetNetEarning() int64 {
	if o == nil || IsNil(o.NetEarning) {
		var ret int64
		return ret
	}
	return *o.NetEarning
}

// GetNetEarningOk returns a tuple with the NetEarning field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MerchantEarning) GetNetEarningOk() (*int64, bool) {
	if o == nil || IsNil(o.NetEarning) {
		return nil, false
	}
	return o.NetEarning, true
}

// HasNetEarning returns a boolean if a field has been set.
func (o *MerchantEarning) HasNetEarning() bool {
	if o != nil && !IsNil(o.NetEarning) {
		return true
	}

	return false
}

// SetNetEarning gets a reference to the given int64 and assigns it to the NetEarning field.
func (o *MerchantEarning) SetNetEarning(v int64) {
	o.NetEarning = &v
}

// GetMexFundDiscount returns the MexFundDiscount field value if set, zero value otherwise.
func (o *MerchantEarning) GetMexFundDiscount() int64 {
	if o == nil || IsNil(o.MexFundDiscount) {
		var ret int64
		return ret
	}
	return *o.MexFundDiscount
}

// GetMexFundDiscountOk returns a tuple with the MexFundDiscount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MerchantEarning) GetMexFundDiscountOk() (*int64, bool) {
	if o == nil || IsNil(o.MexFundDiscount) {
		return nil, false
	}
	return o.MexFundDiscount, true
}

// HasMexFundDiscount returns a boolean if a field has been set.
func (o *MerchantEarning) HasMexFundDiscount() bool {
	if o != nil && !IsNil(o.MexFundDiscount) {
		return true
	}

	return false
}

// SetMexFundDiscount gets a reference to the given int64 and assigns it to the MexFundDiscount field.
func (o *MerchantEarning) SetMexFundDiscount(v int64) {
	o.MexFundDiscount = &v
}

// GetCommission returns the Commission field value if set, zero value otherwise.
func (o *MerchantEarning) GetCommission() int64 {
	if o == nil || IsNil(o.Commission) {
		var ret int64
		return ret
	}
	return *o.Commission
}

// GetCommissionOk returns a tuple with the Commission field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MerchantEarning) GetCommissionOk() (*int64, bool) {
	if o == nil || IsNil(o.Commission) {
		return nil, false
	}
	return o.Commission, true
}

// HasCommission returns a boolean if a field has been set.
func (o *MerchantEarning) HasCommission() bool {
	if o != nil && !IsNil(o.Commission) {
		return true
	}

	return false
}

// SetCommission gets a reference to the given int64 and assigns it to the Commission field.
func (o *MerchantEarning) SetCommission(v int64) {
	o.Commission = &v
}

func (o MerchantEarning) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MerchantEarning) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Revenue) {
		toSerialize["revenue"] = o.Revenue
	}
	if !IsNil(o.NetEarning) {
		toSerialize["netEarning"] = o.NetEarning
	}
	if !IsNil(o.MexFundDiscount) {
		toSerialize["mexFundDiscount"] = o.MexFundDiscount
	}
	if !IsNil(o.Commission) {
		toSerialize["commission"] = o.Commission
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MerchantEarning) UnmarshalJSON(data []byte) (err error) {
	varMerchantEarning := _MerchantEarning{}

	err = json.Unmarshal(data, &varMerchantEarning)

	if err != nil {
		return err
	}

	*o = MerchantEarning(varMerchantEarning)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "revenue")
		delete(additionalProperties, "netEarning")
		delete(additionalProperties, "mexFundDiscount")
		delete(additionalProperties, "commission")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMerchantEarning struct {
	value *MerchantEarning
	isSet bool
}

func (v NullableMerchantEarning) Get() *MerchantEarning {
	return v.value
}

func (v *NullableMerchantEarning) Set(val *MerchantEarning) {
	v.value = val
	v.isSet = true
}

func (v NullableMerchantEarning) IsSet() bool {
	return v.isSet
}

func (v *NullableMerchantEarning) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMerchantEarning(val *MerchantEarning) *NullableMerchantEarning {
	return &NullableMerchantEarning{value: val, isSet: true}
}

func (v NullableMerchantEarning) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMerchantEarning) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


