// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
GrabFood

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.1.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package grabfood

import (
	"encoding/json"
)

// checks if the SyncPOSOrderResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SyncPOSOrderResponse{}

// SyncPOSOrderResponse The Sync POS Order response, include grab order ID and paybill QR deeplink
type SyncPOSOrderResponse struct {
	// The orderID in grab system.
	OrderID *string `json:"orderID,omitempty"`
	// The paybill QR Code.
	PaybillQRCode *string `json:"paybillQRCode,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SyncPOSOrderResponse SyncPOSOrderResponse

// NewSyncPOSOrderResponse instantiates a new SyncPOSOrderResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSyncPOSOrderResponse() *SyncPOSOrderResponse {
	this := SyncPOSOrderResponse{}
	return &this
}

// NewSyncPOSOrderResponseWithDefaults instantiates a new SyncPOSOrderResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSyncPOSOrderResponseWithDefaults() *SyncPOSOrderResponse {
	this := SyncPOSOrderResponse{}
	return &this
}

// GetOrderID returns the OrderID field value if set, zero value otherwise.
func (o *SyncPOSOrderResponse) GetOrderID() string {
	if o == nil || IsNil(o.OrderID) {
		var ret string
		return ret
	}
	return *o.OrderID
}

// GetOrderIDOk returns a tuple with the OrderID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SyncPOSOrderResponse) GetOrderIDOk() (*string, bool) {
	if o == nil || IsNil(o.OrderID) {
		return nil, false
	}
	return o.OrderID, true
}

// HasOrderID returns a boolean if a field has been set.
func (o *SyncPOSOrderResponse) HasOrderID() bool {
	if o != nil && !IsNil(o.OrderID) {
		return true
	}

	return false
}

// SetOrderID gets a reference to the given string and assigns it to the OrderID field.
func (o *SyncPOSOrderResponse) SetOrderID(v string) {
	o.OrderID = &v
}

// GetPaybillQRCode returns the PaybillQRCode field value if set, zero value otherwise.
func (o *SyncPOSOrderResponse) GetPaybillQRCode() string {
	if o == nil || IsNil(o.PaybillQRCode) {
		var ret string
		return ret
	}
	return *o.PaybillQRCode
}

// GetPaybillQRCodeOk returns a tuple with the PaybillQRCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SyncPOSOrderResponse) GetPaybillQRCodeOk() (*string, bool) {
	if o == nil || IsNil(o.PaybillQRCode) {
		return nil, false
	}
	return o.PaybillQRCode, true
}

// HasPaybillQRCode returns a boolean if a field has been set.
func (o *SyncPOSOrderResponse) HasPaybillQRCode() bool {
	if o != nil && !IsNil(o.PaybillQRCode) {
		return true
	}

	return false
}

// SetPaybillQRCode gets a reference to the given string and assigns it to the PaybillQRCode field.
func (o *SyncPOSOrderResponse) SetPaybillQRCode(v string) {
	o.PaybillQRCode = &v
}

func (o SyncPOSOrderResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SyncPOSOrderResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.OrderID) {
		toSerialize["orderID"] = o.OrderID
	}
	if !IsNil(o.PaybillQRCode) {
		toSerialize["paybillQRCode"] = o.PaybillQRCode
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SyncPOSOrderResponse) UnmarshalJSON(data []byte) (err error) {
	varSyncPOSOrderResponse := _SyncPOSOrderResponse{}

	err = json.Unmarshal(data, &varSyncPOSOrderResponse)

	if err != nil {
		return err
	}

	*o = SyncPOSOrderResponse(varSyncPOSOrderResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "orderID")
		delete(additionalProperties, "paybillQRCode")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSyncPOSOrderResponse struct {
	value *SyncPOSOrderResponse
	isSet bool
}

func (v NullableSyncPOSOrderResponse) Get() *SyncPOSOrderResponse {
	return v.value
}

func (v *NullableSyncPOSOrderResponse) Set(val *SyncPOSOrderResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSyncPOSOrderResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSyncPOSOrderResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSyncPOSOrderResponse(val *SyncPOSOrderResponse) *NullableSyncPOSOrderResponse {
	return &NullableSyncPOSOrderResponse{value: val, isSet: true}
}

func (v NullableSyncPOSOrderResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSyncPOSOrderResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


