// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
GrabFood

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.1.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package grabfood

import (
	"encoding/json"
)

// checks if the AdvancedPricing type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdvancedPricing{}

// AdvancedPricing Price configuration (in minor unit) for different service, order type and channel combination. If a service type does not have a specified price, it will utilize the default price of the item. Refer [Service Based Menu](#section/Service-Based-Menu). 
type AdvancedPricing struct {
	// Service type: `Delivery`, Order type: `Instant`, Channel: `Grab App` 
	DeliveryOnDemandGrabApp *int64 `json:"Delivery_OnDemand_GrabApp,omitempty"`
	// Service type: `Delivery`, Order type: `Scheduled`, Channel: `Grab App` 
	DeliveryScheduledGrabApp *int64 `json:"Delivery_Scheduled_GrabApp,omitempty"`
	// Service type: `Self Pick Up`, Order type: `Instant`, Channel: `Grab App` 
	SelfPickUpOnDemandGrabApp *int64 `json:"SelfPickUp_OnDemand_GrabApp,omitempty"`
	// Service type: `Dine In`, Order type: `Instant`, Channel: `Grab App` 
	DineInOnDemandGrabApp *int64 `json:"DineIn_OnDemand_GrabApp,omitempty"`
	// Service type: `Delivery`, Order type: `Instant`, Channel: `Store Front` 
	DeliveryOnDemandStoreFront *int64 `json:"Delivery_OnDemand_StoreFront,omitempty"`
	// Service type: `Delivery`, Order type: `Scheduled`, Channel: `Store Front` 
	DeliveryScheduledStoreFront *int64 `json:"Delivery_Scheduled_StoreFront,omitempty"`
	// Service type: `Self Pick Up`, Order type: `Instant`, Channel: `Store Front` 
	SelfPickUpOnDemandStoreFront *int64 `json:"SelfPickUp_OnDemand_StoreFront,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AdvancedPricing AdvancedPricing

// NewAdvancedPricing instantiates a new AdvancedPricing object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdvancedPricing() *AdvancedPricing {
	this := AdvancedPricing{}
	return &this
}

// NewAdvancedPricingWithDefaults instantiates a new AdvancedPricing object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdvancedPricingWithDefaults() *AdvancedPricing {
	this := AdvancedPricing{}
	return &this
}

// GetDeliveryOnDemandGrabApp returns the DeliveryOnDemandGrabApp field value if set, zero value otherwise.
func (o *AdvancedPricing) GetDeliveryOnDemandGrabApp() int64 {
	if o == nil || IsNil(o.DeliveryOnDemandGrabApp) {
		var ret int64
		return ret
	}
	return *o.DeliveryOnDemandGrabApp
}

// GetDeliveryOnDemandGrabAppOk returns a tuple with the DeliveryOnDemandGrabApp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvancedPricing) GetDeliveryOnDemandGrabAppOk() (*int64, bool) {
	if o == nil || IsNil(o.DeliveryOnDemandGrabApp) {
		return nil, false
	}
	return o.DeliveryOnDemandGrabApp, true
}

// HasDeliveryOnDemandGrabApp returns a boolean if a field has been set.
func (o *AdvancedPricing) HasDeliveryOnDemandGrabApp() bool {
	if o != nil && !IsNil(o.DeliveryOnDemandGrabApp) {
		return true
	}

	return false
}

// SetDeliveryOnDemandGrabApp gets a reference to the given int64 and assigns it to the DeliveryOnDemandGrabApp field.
func (o *AdvancedPricing) SetDeliveryOnDemandGrabApp(v int64) {
	o.DeliveryOnDemandGrabApp = &v
}

// GetDeliveryScheduledGrabApp returns the DeliveryScheduledGrabApp field value if set, zero value otherwise.
func (o *AdvancedPricing) GetDeliveryScheduledGrabApp() int64 {
	if o == nil || IsNil(o.DeliveryScheduledGrabApp) {
		var ret int64
		return ret
	}
	return *o.DeliveryScheduledGrabApp
}

// GetDeliveryScheduledGrabAppOk returns a tuple with the DeliveryScheduledGrabApp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvancedPricing) GetDeliveryScheduledGrabAppOk() (*int64, bool) {
	if o == nil || IsNil(o.DeliveryScheduledGrabApp) {
		return nil, false
	}
	return o.DeliveryScheduledGrabApp, true
}

// HasDeliveryScheduledGrabApp returns a boolean if a field has been set.
func (o *AdvancedPricing) HasDeliveryScheduledGrabApp() bool {
	if o != nil && !IsNil(o.DeliveryScheduledGrabApp) {
		return true
	}

	return false
}

// SetDeliveryScheduledGrabApp gets a reference to the given int64 and assigns it to the DeliveryScheduledGrabApp field.
func (o *AdvancedPricing) SetDeliveryScheduledGrabApp(v int64) {
	o.DeliveryScheduledGrabApp = &v
}

// GetSelfPickUpOnDemandGrabApp returns the SelfPickUpOnDemandGrabApp field value if set, zero value otherwise.
func (o *AdvancedPricing) GetSelfPickUpOnDemandGrabApp() int64 {
	if o == nil || IsNil(o.SelfPickUpOnDemandGrabApp) {
		var ret int64
		return ret
	}
	return *o.SelfPickUpOnDemandGrabApp
}

// GetSelfPickUpOnDemandGrabAppOk returns a tuple with the SelfPickUpOnDemandGrabApp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvancedPricing) GetSelfPickUpOnDemandGrabAppOk() (*int64, bool) {
	if o == nil || IsNil(o.SelfPickUpOnDemandGrabApp) {
		return nil, false
	}
	return o.SelfPickUpOnDemandGrabApp, true
}

// HasSelfPickUpOnDemandGrabApp returns a boolean if a field has been set.
func (o *AdvancedPricing) HasSelfPickUpOnDemandGrabApp() bool {
	if o != nil && !IsNil(o.SelfPickUpOnDemandGrabApp) {
		return true
	}

	return false
}

// SetSelfPickUpOnDemandGrabApp gets a reference to the given int64 and assigns it to the SelfPickUpOnDemandGrabApp field.
func (o *AdvancedPricing) SetSelfPickUpOnDemandGrabApp(v int64) {
	o.SelfPickUpOnDemandGrabApp = &v
}

// GetDineInOnDemandGrabApp returns the DineInOnDemandGrabApp field value if set, zero value otherwise.
func (o *AdvancedPricing) GetDineInOnDemandGrabApp() int64 {
	if o == nil || IsNil(o.DineInOnDemandGrabApp) {
		var ret int64
		return ret
	}
	return *o.DineInOnDemandGrabApp
}

// GetDineInOnDemandGrabAppOk returns a tuple with the DineInOnDemandGrabApp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvancedPricing) GetDineInOnDemandGrabAppOk() (*int64, bool) {
	if o == nil || IsNil(o.DineInOnDemandGrabApp) {
		return nil, false
	}
	return o.DineInOnDemandGrabApp, true
}

// HasDineInOnDemandGrabApp returns a boolean if a field has been set.
func (o *AdvancedPricing) HasDineInOnDemandGrabApp() bool {
	if o != nil && !IsNil(o.DineInOnDemandGrabApp) {
		return true
	}

	return false
}

// SetDineInOnDemandGrabApp gets a reference to the given int64 and assigns it to the DineInOnDemandGrabApp field.
func (o *AdvancedPricing) SetDineInOnDemandGrabApp(v int64) {
	o.DineInOnDemandGrabApp = &v
}

// GetDeliveryOnDemandStoreFront returns the DeliveryOnDemandStoreFront field value if set, zero value otherwise.
func (o *AdvancedPricing) GetDeliveryOnDemandStoreFront() int64 {
	if o == nil || IsNil(o.DeliveryOnDemandStoreFront) {
		var ret int64
		return ret
	}
	return *o.DeliveryOnDemandStoreFront
}

// GetDeliveryOnDemandStoreFrontOk returns a tuple with the DeliveryOnDemandStoreFront field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvancedPricing) GetDeliveryOnDemandStoreFrontOk() (*int64, bool) {
	if o == nil || IsNil(o.DeliveryOnDemandStoreFront) {
		return nil, false
	}
	return o.DeliveryOnDemandStoreFront, true
}

// HasDeliveryOnDemandStoreFront returns a boolean if a field has been set.
func (o *AdvancedPricing) HasDeliveryOnDemandStoreFront() bool {
	if o != nil && !IsNil(o.DeliveryOnDemandStoreFront) {
		return true
	}

	return false
}

// SetDeliveryOnDemandStoreFront gets a reference to the given int64 and assigns it to the DeliveryOnDemandStoreFront field.
func (o *AdvancedPricing) SetDeliveryOnDemandStoreFront(v int64) {
	o.DeliveryOnDemandStoreFront = &v
}

// GetDeliveryScheduledStoreFront returns the DeliveryScheduledStoreFront field value if set, zero value otherwise.
func (o *AdvancedPricing) GetDeliveryScheduledStoreFront() int64 {
	if o == nil || IsNil(o.DeliveryScheduledStoreFront) {
		var ret int64
		return ret
	}
	return *o.DeliveryScheduledStoreFront
}

// GetDeliveryScheduledStoreFrontOk returns a tuple with the DeliveryScheduledStoreFront field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvancedPricing) GetDeliveryScheduledStoreFrontOk() (*int64, bool) {
	if o == nil || IsNil(o.DeliveryScheduledStoreFront) {
		return nil, false
	}
	return o.DeliveryScheduledStoreFront, true
}

// HasDeliveryScheduledStoreFront returns a boolean if a field has been set.
func (o *AdvancedPricing) HasDeliveryScheduledStoreFront() bool {
	if o != nil && !IsNil(o.DeliveryScheduledStoreFront) {
		return true
	}

	return false
}

// SetDeliveryScheduledStoreFront gets a reference to the given int64 and assigns it to the DeliveryScheduledStoreFront field.
func (o *AdvancedPricing) SetDeliveryScheduledStoreFront(v int64) {
	o.DeliveryScheduledStoreFront = &v
}

// GetSelfPickUpOnDemandStoreFront returns the SelfPickUpOnDemandStoreFront field value if set, zero value otherwise.
func (o *AdvancedPricing) GetSelfPickUpOnDemandStoreFront() int64 {
	if o == nil || IsNil(o.SelfPickUpOnDemandStoreFront) {
		var ret int64
		return ret
	}
	return *o.SelfPickUpOnDemandStoreFront
}

// GetSelfPickUpOnDemandStoreFrontOk returns a tuple with the SelfPickUpOnDemandStoreFront field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvancedPricing) GetSelfPickUpOnDemandStoreFrontOk() (*int64, bool) {
	if o == nil || IsNil(o.SelfPickUpOnDemandStoreFront) {
		return nil, false
	}
	return o.SelfPickUpOnDemandStoreFront, true
}

// HasSelfPickUpOnDemandStoreFront returns a boolean if a field has been set.
func (o *AdvancedPricing) HasSelfPickUpOnDemandStoreFront() bool {
	if o != nil && !IsNil(o.SelfPickUpOnDemandStoreFront) {
		return true
	}

	return false
}

// SetSelfPickUpOnDemandStoreFront gets a reference to the given int64 and assigns it to the SelfPickUpOnDemandStoreFront field.
func (o *AdvancedPricing) SetSelfPickUpOnDemandStoreFront(v int64) {
	o.SelfPickUpOnDemandStoreFront = &v
}

func (o AdvancedPricing) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdvancedPricing) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DeliveryOnDemandGrabApp) {
		toSerialize["Delivery_OnDemand_GrabApp"] = o.DeliveryOnDemandGrabApp
	}
	if !IsNil(o.DeliveryScheduledGrabApp) {
		toSerialize["Delivery_Scheduled_GrabApp"] = o.DeliveryScheduledGrabApp
	}
	if !IsNil(o.SelfPickUpOnDemandGrabApp) {
		toSerialize["SelfPickUp_OnDemand_GrabApp"] = o.SelfPickUpOnDemandGrabApp
	}
	if !IsNil(o.DineInOnDemandGrabApp) {
		toSerialize["DineIn_OnDemand_GrabApp"] = o.DineInOnDemandGrabApp
	}
	if !IsNil(o.DeliveryOnDemandStoreFront) {
		toSerialize["Delivery_OnDemand_StoreFront"] = o.DeliveryOnDemandStoreFront
	}
	if !IsNil(o.DeliveryScheduledStoreFront) {
		toSerialize["Delivery_Scheduled_StoreFront"] = o.DeliveryScheduledStoreFront
	}
	if !IsNil(o.SelfPickUpOnDemandStoreFront) {
		toSerialize["SelfPickUp_OnDemand_StoreFront"] = o.SelfPickUpOnDemandStoreFront
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AdvancedPricing) UnmarshalJSON(data []byte) (err error) {
	varAdvancedPricing := _AdvancedPricing{}

	err = json.Unmarshal(data, &varAdvancedPricing)

	if err != nil {
		return err
	}

	*o = AdvancedPricing(varAdvancedPricing)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "Delivery_OnDemand_GrabApp")
		delete(additionalProperties, "Delivery_Scheduled_GrabApp")
		delete(additionalProperties, "SelfPickUp_OnDemand_GrabApp")
		delete(additionalProperties, "DineIn_OnDemand_GrabApp")
		delete(additionalProperties, "Delivery_OnDemand_StoreFront")
		delete(additionalProperties, "Delivery_Scheduled_StoreFront")
		delete(additionalProperties, "SelfPickUp_OnDemand_StoreFront")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAdvancedPricing struct {
	value *AdvancedPricing
	isSet bool
}

func (v NullableAdvancedPricing) Get() *AdvancedPricing {
	return v.value
}

func (v *NullableAdvancedPricing) Set(val *AdvancedPricing) {
	v.value = val
	v.isSet = true
}

func (v NullableAdvancedPricing) IsSet() bool {
	return v.isSet
}

func (v *NullableAdvancedPricing) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdvancedPricing(val *AdvancedPricing) *NullableAdvancedPricing {
	return &NullableAdvancedPricing{value: val, isSet: true}
}

func (v NullableAdvancedPricing) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdvancedPricing) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


