// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
GrabFood

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.1.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package grabfood

import (
	"encoding/json"
)

// checks if the Coordinates type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Coordinates{}

// Coordinates A JSON object containing the coordinates of the delivery address. Only has value when poiSource is `GRAB`.
type Coordinates struct {
	// The latitude coordinates of the delivery address.
	Latitude *float64 `json:"latitude,omitempty"`
	// The longitude coordinates of the delivery address.
	Longitude *float64 `json:"longitude,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _Coordinates Coordinates

// NewCoordinates instantiates a new Coordinates object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCoordinates() *Coordinates {
	this := Coordinates{}
	return &this
}

// NewCoordinatesWithDefaults instantiates a new Coordinates object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCoordinatesWithDefaults() *Coordinates {
	this := Coordinates{}
	return &this
}

// GetLatitude returns the Latitude field value if set, zero value otherwise.
func (o *Coordinates) GetLatitude() float64 {
	if o == nil || IsNil(o.Latitude) {
		var ret float64
		return ret
	}
	return *o.Latitude
}

// GetLatitudeOk returns a tuple with the Latitude field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Coordinates) GetLatitudeOk() (*float64, bool) {
	if o == nil || IsNil(o.Latitude) {
		return nil, false
	}
	return o.Latitude, true
}

// HasLatitude returns a boolean if a field has been set.
func (o *Coordinates) HasLatitude() bool {
	if o != nil && !IsNil(o.Latitude) {
		return true
	}

	return false
}

// SetLatitude gets a reference to the given float64 and assigns it to the Latitude field.
func (o *Coordinates) SetLatitude(v float64) {
	o.Latitude = &v
}

// GetLongitude returns the Longitude field value if set, zero value otherwise.
func (o *Coordinates) GetLongitude() float64 {
	if o == nil || IsNil(o.Longitude) {
		var ret float64
		return ret
	}
	return *o.Longitude
}

// GetLongitudeOk returns a tuple with the Longitude field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Coordinates) GetLongitudeOk() (*float64, bool) {
	if o == nil || IsNil(o.Longitude) {
		return nil, false
	}
	return o.Longitude, true
}

// HasLongitude returns a boolean if a field has been set.
func (o *Coordinates) HasLongitude() bool {
	if o != nil && !IsNil(o.Longitude) {
		return true
	}

	return false
}

// SetLongitude gets a reference to the given float64 and assigns it to the Longitude field.
func (o *Coordinates) SetLongitude(v float64) {
	o.Longitude = &v
}

func (o Coordinates) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Coordinates) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Latitude) {
		toSerialize["latitude"] = o.Latitude
	}
	if !IsNil(o.Longitude) {
		toSerialize["longitude"] = o.Longitude
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Coordinates) UnmarshalJSON(data []byte) (err error) {
	varCoordinates := _Coordinates{}

	err = json.Unmarshal(data, &varCoordinates)

	if err != nil {
		return err
	}

	*o = Coordinates(varCoordinates)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "latitude")
		delete(additionalProperties, "longitude")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCoordinates struct {
	value *Coordinates
	isSet bool
}

func (v NullableCoordinates) Get() *Coordinates {
	return v.value
}

func (v *NullableCoordinates) Set(val *Coordinates) {
	v.value = val
	v.isSet = true
}

func (v NullableCoordinates) IsSet() bool {
	return v.isSet
}

func (v *NullableCoordinates) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCoordinates(val *Coordinates) *NullableCoordinates {
	return &NullableCoordinates{value: val, isSet: true}
}

func (v NullableCoordinates) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCoordinates) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


