// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
GrabFood

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.1.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package grabfood

import (
	"encoding/json"
)

// checks if the Purchasability type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Purchasability{}

// Purchasability Purchasability is set to true by default for all service type, unless it is explicitly set to false. Modifier will reuse it’s item’s purchasability. Refer [Service Based Menu](#section/Service-Based-Menu). 
type Purchasability struct {
	DeliveryOnDemandGrabApp *bool `json:"Delivery_OnDemand_GrabApp,omitempty"`
	DeliveryScheduledGrabApp *bool `json:"Delivery_Scheduled_GrabApp,omitempty"`
	SelfPickUpOnDemandGrabApp *bool `json:"SelfPickUp_OnDemand_GrabApp,omitempty"`
	DineInOnDemandGrabApp *bool `json:"DineIn_OnDemand_GrabApp,omitempty"`
	DeliveryOnDemandStoreFront *bool `json:"Delivery_OnDemand_StoreFront,omitempty"`
	DeliveryScheduledStoreFront *bool `json:"Delivery_Scheduled_StoreFront,omitempty"`
	SelfPickUpOnDemandStoreFront *bool `json:"SelfPickUp_OnDemand_StoreFront,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _Purchasability Purchasability

// NewPurchasability instantiates a new Purchasability object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPurchasability() *Purchasability {
	this := Purchasability{}
	return &this
}

// NewPurchasabilityWithDefaults instantiates a new Purchasability object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPurchasabilityWithDefaults() *Purchasability {
	this := Purchasability{}
	return &this
}

// GetDeliveryOnDemandGrabApp returns the DeliveryOnDemandGrabApp field value if set, zero value otherwise.
func (o *Purchasability) GetDeliveryOnDemandGrabApp() bool {
	if o == nil || IsNil(o.DeliveryOnDemandGrabApp) {
		var ret bool
		return ret
	}
	return *o.DeliveryOnDemandGrabApp
}

// GetDeliveryOnDemandGrabAppOk returns a tuple with the DeliveryOnDemandGrabApp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Purchasability) GetDeliveryOnDemandGrabAppOk() (*bool, bool) {
	if o == nil || IsNil(o.DeliveryOnDemandGrabApp) {
		return nil, false
	}
	return o.DeliveryOnDemandGrabApp, true
}

// HasDeliveryOnDemandGrabApp returns a boolean if a field has been set.
func (o *Purchasability) HasDeliveryOnDemandGrabApp() bool {
	if o != nil && !IsNil(o.DeliveryOnDemandGrabApp) {
		return true
	}

	return false
}

// SetDeliveryOnDemandGrabApp gets a reference to the given bool and assigns it to the DeliveryOnDemandGrabApp field.
func (o *Purchasability) SetDeliveryOnDemandGrabApp(v bool) {
	o.DeliveryOnDemandGrabApp = &v
}

// GetDeliveryScheduledGrabApp returns the DeliveryScheduledGrabApp field value if set, zero value otherwise.
func (o *Purchasability) GetDeliveryScheduledGrabApp() bool {
	if o == nil || IsNil(o.DeliveryScheduledGrabApp) {
		var ret bool
		return ret
	}
	return *o.DeliveryScheduledGrabApp
}

// GetDeliveryScheduledGrabAppOk returns a tuple with the DeliveryScheduledGrabApp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Purchasability) GetDeliveryScheduledGrabAppOk() (*bool, bool) {
	if o == nil || IsNil(o.DeliveryScheduledGrabApp) {
		return nil, false
	}
	return o.DeliveryScheduledGrabApp, true
}

// HasDeliveryScheduledGrabApp returns a boolean if a field has been set.
func (o *Purchasability) HasDeliveryScheduledGrabApp() bool {
	if o != nil && !IsNil(o.DeliveryScheduledGrabApp) {
		return true
	}

	return false
}

// SetDeliveryScheduledGrabApp gets a reference to the given bool and assigns it to the DeliveryScheduledGrabApp field.
func (o *Purchasability) SetDeliveryScheduledGrabApp(v bool) {
	o.DeliveryScheduledGrabApp = &v
}

// GetSelfPickUpOnDemandGrabApp returns the SelfPickUpOnDemandGrabApp field value if set, zero value otherwise.
func (o *Purchasability) GetSelfPickUpOnDemandGrabApp() bool {
	if o == nil || IsNil(o.SelfPickUpOnDemandGrabApp) {
		var ret bool
		return ret
	}
	return *o.SelfPickUpOnDemandGrabApp
}

// GetSelfPickUpOnDemandGrabAppOk returns a tuple with the SelfPickUpOnDemandGrabApp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Purchasability) GetSelfPickUpOnDemandGrabAppOk() (*bool, bool) {
	if o == nil || IsNil(o.SelfPickUpOnDemandGrabApp) {
		return nil, false
	}
	return o.SelfPickUpOnDemandGrabApp, true
}

// HasSelfPickUpOnDemandGrabApp returns a boolean if a field has been set.
func (o *Purchasability) HasSelfPickUpOnDemandGrabApp() bool {
	if o != nil && !IsNil(o.SelfPickUpOnDemandGrabApp) {
		return true
	}

	return false
}

// SetSelfPickUpOnDemandGrabApp gets a reference to the given bool and assigns it to the SelfPickUpOnDemandGrabApp field.
func (o *Purchasability) SetSelfPickUpOnDemandGrabApp(v bool) {
	o.SelfPickUpOnDemandGrabApp = &v
}

// GetDineInOnDemandGrabApp returns the DineInOnDemandGrabApp field value if set, zero value otherwise.
func (o *Purchasability) GetDineInOnDemandGrabApp() bool {
	if o == nil || IsNil(o.DineInOnDemandGrabApp) {
		var ret bool
		return ret
	}
	return *o.DineInOnDemandGrabApp
}

// GetDineInOnDemandGrabAppOk returns a tuple with the DineInOnDemandGrabApp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Purchasability) GetDineInOnDemandGrabAppOk() (*bool, bool) {
	if o == nil || IsNil(o.DineInOnDemandGrabApp) {
		return nil, false
	}
	return o.DineInOnDemandGrabApp, true
}

// HasDineInOnDemandGrabApp returns a boolean if a field has been set.
func (o *Purchasability) HasDineInOnDemandGrabApp() bool {
	if o != nil && !IsNil(o.DineInOnDemandGrabApp) {
		return true
	}

	return false
}

// SetDineInOnDemandGrabApp gets a reference to the given bool and assigns it to the DineInOnDemandGrabApp field.
func (o *Purchasability) SetDineInOnDemandGrabApp(v bool) {
	o.DineInOnDemandGrabApp = &v
}

// GetDeliveryOnDemandStoreFront returns the DeliveryOnDemandStoreFront field value if set, zero value otherwise.
func (o *Purchasability) GetDeliveryOnDemandStoreFront() bool {
	if o == nil || IsNil(o.DeliveryOnDemandStoreFront) {
		var ret bool
		return ret
	}
	return *o.DeliveryOnDemandStoreFront
}

// GetDeliveryOnDemandStoreFrontOk returns a tuple with the DeliveryOnDemandStoreFront field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Purchasability) GetDeliveryOnDemandStoreFrontOk() (*bool, bool) {
	if o == nil || IsNil(o.DeliveryOnDemandStoreFront) {
		return nil, false
	}
	return o.DeliveryOnDemandStoreFront, true
}

// HasDeliveryOnDemandStoreFront returns a boolean if a field has been set.
func (o *Purchasability) HasDeliveryOnDemandStoreFront() bool {
	if o != nil && !IsNil(o.DeliveryOnDemandStoreFront) {
		return true
	}

	return false
}

// SetDeliveryOnDemandStoreFront gets a reference to the given bool and assigns it to the DeliveryOnDemandStoreFront field.
func (o *Purchasability) SetDeliveryOnDemandStoreFront(v bool) {
	o.DeliveryOnDemandStoreFront = &v
}

// GetDeliveryScheduledStoreFront returns the DeliveryScheduledStoreFront field value if set, zero value otherwise.
func (o *Purchasability) GetDeliveryScheduledStoreFront() bool {
	if o == nil || IsNil(o.DeliveryScheduledStoreFront) {
		var ret bool
		return ret
	}
	return *o.DeliveryScheduledStoreFront
}

// GetDeliveryScheduledStoreFrontOk returns a tuple with the DeliveryScheduledStoreFront field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Purchasability) GetDeliveryScheduledStoreFrontOk() (*bool, bool) {
	if o == nil || IsNil(o.DeliveryScheduledStoreFront) {
		return nil, false
	}
	return o.DeliveryScheduledStoreFront, true
}

// HasDeliveryScheduledStoreFront returns a boolean if a field has been set.
func (o *Purchasability) HasDeliveryScheduledStoreFront() bool {
	if o != nil && !IsNil(o.DeliveryScheduledStoreFront) {
		return true
	}

	return false
}

// SetDeliveryScheduledStoreFront gets a reference to the given bool and assigns it to the DeliveryScheduledStoreFront field.
func (o *Purchasability) SetDeliveryScheduledStoreFront(v bool) {
	o.DeliveryScheduledStoreFront = &v
}

// GetSelfPickUpOnDemandStoreFront returns the SelfPickUpOnDemandStoreFront field value if set, zero value otherwise.
func (o *Purchasability) GetSelfPickUpOnDemandStoreFront() bool {
	if o == nil || IsNil(o.SelfPickUpOnDemandStoreFront) {
		var ret bool
		return ret
	}
	return *o.SelfPickUpOnDemandStoreFront
}

// GetSelfPickUpOnDemandStoreFrontOk returns a tuple with the SelfPickUpOnDemandStoreFront field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Purchasability) GetSelfPickUpOnDemandStoreFrontOk() (*bool, bool) {
	if o == nil || IsNil(o.SelfPickUpOnDemandStoreFront) {
		return nil, false
	}
	return o.SelfPickUpOnDemandStoreFront, true
}

// HasSelfPickUpOnDemandStoreFront returns a boolean if a field has been set.
func (o *Purchasability) HasSelfPickUpOnDemandStoreFront() bool {
	if o != nil && !IsNil(o.SelfPickUpOnDemandStoreFront) {
		return true
	}

	return false
}

// SetSelfPickUpOnDemandStoreFront gets a reference to the given bool and assigns it to the SelfPickUpOnDemandStoreFront field.
func (o *Purchasability) SetSelfPickUpOnDemandStoreFront(v bool) {
	o.SelfPickUpOnDemandStoreFront = &v
}

func (o Purchasability) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Purchasability) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DeliveryOnDemandGrabApp) {
		toSerialize["Delivery_OnDemand_GrabApp"] = o.DeliveryOnDemandGrabApp
	}
	if !IsNil(o.DeliveryScheduledGrabApp) {
		toSerialize["Delivery_Scheduled_GrabApp"] = o.DeliveryScheduledGrabApp
	}
	if !IsNil(o.SelfPickUpOnDemandGrabApp) {
		toSerialize["SelfPickUp_OnDemand_GrabApp"] = o.SelfPickUpOnDemandGrabApp
	}
	if !IsNil(o.DineInOnDemandGrabApp) {
		toSerialize["DineIn_OnDemand_GrabApp"] = o.DineInOnDemandGrabApp
	}
	if !IsNil(o.DeliveryOnDemandStoreFront) {
		toSerialize["Delivery_OnDemand_StoreFront"] = o.DeliveryOnDemandStoreFront
	}
	if !IsNil(o.DeliveryScheduledStoreFront) {
		toSerialize["Delivery_Scheduled_StoreFront"] = o.DeliveryScheduledStoreFront
	}
	if !IsNil(o.SelfPickUpOnDemandStoreFront) {
		toSerialize["SelfPickUp_OnDemand_StoreFront"] = o.SelfPickUpOnDemandStoreFront
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Purchasability) UnmarshalJSON(data []byte) (err error) {
	varPurchasability := _Purchasability{}

	err = json.Unmarshal(data, &varPurchasability)

	if err != nil {
		return err
	}

	*o = Purchasability(varPurchasability)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "Delivery_OnDemand_GrabApp")
		delete(additionalProperties, "Delivery_Scheduled_GrabApp")
		delete(additionalProperties, "SelfPickUp_OnDemand_GrabApp")
		delete(additionalProperties, "DineIn_OnDemand_GrabApp")
		delete(additionalProperties, "Delivery_OnDemand_StoreFront")
		delete(additionalProperties, "Delivery_Scheduled_StoreFront")
		delete(additionalProperties, "SelfPickUp_OnDemand_StoreFront")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePurchasability struct {
	value *Purchasability
	isSet bool
}

func (v NullablePurchasability) Get() *Purchasability {
	return v.value
}

func (v *NullablePurchasability) Set(val *Purchasability) {
	v.value = val
	v.isSet = true
}

func (v NullablePurchasability) IsSet() bool {
	return v.isSet
}

func (v *NullablePurchasability) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePurchasability(val *Purchasability) *NullablePurchasability {
	return &NullablePurchasability{value: val, isSet: true}
}

func (v NullablePurchasability) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePurchasability) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


