// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
GrabFood

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.1.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package grabfood

import (
	"encoding/json"
)

// checks if the OrderCampaign type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrderCampaign{}

// OrderCampaign struct for OrderCampaign
type OrderCampaign struct {
	// The campaign's ID returned by GrabFood upon campaign creation.
	Id *string `json:"id,omitempty"`
	// The name of the campaign. This campaign name has been automatically generated by Grab for display in the customer app.
	Name *string `json:"name,omitempty"`
	// The campaign name provided by the merchant in [Create Campaign](#tag/create-campaign). Whitelist required, reach out to your integration manager.
	CampaignNameForMex *string `json:"campaignNameForMex,omitempty"`
	// The campaign level.
	Level *string `json:"level,omitempty"`
	// The type of campaign.
	Type *string `json:"type,omitempty"`
	// The campaign redemption count in this order.
	UsageCount *int64 `json:"usageCount,omitempty"`
	// The ratio funded by the merchant in percentage.
	MexFundedRatio *int32 `json:"mexFundedRatio,omitempty"`
	// The deducted amount in minor unit format. `Item price(tax inclusive) * 20% discount | 2375*0.2`
	DeductedAmount *int64 `json:"deductedAmount,omitempty"`
	// The part that the campaign is applied.
	DeductedPart *string `json:"deductedPart,omitempty"`
	// An array of item IDs that get discount under this campaign. `null` if no item applied in this campaign.
	AppliedItemIDs []string `json:"appliedItemIDs,omitempty"`
	FreeItem *OrderFreeItem `json:"freeItem,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _OrderCampaign OrderCampaign

// NewOrderCampaign instantiates a new OrderCampaign object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderCampaign() *OrderCampaign {
	this := OrderCampaign{}
	return &this
}

// NewOrderCampaignWithDefaults instantiates a new OrderCampaign object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderCampaignWithDefaults() *OrderCampaign {
	this := OrderCampaign{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *OrderCampaign) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCampaign) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *OrderCampaign) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *OrderCampaign) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *OrderCampaign) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCampaign) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *OrderCampaign) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *OrderCampaign) SetName(v string) {
	o.Name = &v
}

// GetCampaignNameForMex returns the CampaignNameForMex field value if set, zero value otherwise.
func (o *OrderCampaign) GetCampaignNameForMex() string {
	if o == nil || IsNil(o.CampaignNameForMex) {
		var ret string
		return ret
	}
	return *o.CampaignNameForMex
}

// GetCampaignNameForMexOk returns a tuple with the CampaignNameForMex field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCampaign) GetCampaignNameForMexOk() (*string, bool) {
	if o == nil || IsNil(o.CampaignNameForMex) {
		return nil, false
	}
	return o.CampaignNameForMex, true
}

// HasCampaignNameForMex returns a boolean if a field has been set.
func (o *OrderCampaign) HasCampaignNameForMex() bool {
	if o != nil && !IsNil(o.CampaignNameForMex) {
		return true
	}

	return false
}

// SetCampaignNameForMex gets a reference to the given string and assigns it to the CampaignNameForMex field.
func (o *OrderCampaign) SetCampaignNameForMex(v string) {
	o.CampaignNameForMex = &v
}

// GetLevel returns the Level field value if set, zero value otherwise.
func (o *OrderCampaign) GetLevel() string {
	if o == nil || IsNil(o.Level) {
		var ret string
		return ret
	}
	return *o.Level
}

// GetLevelOk returns a tuple with the Level field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCampaign) GetLevelOk() (*string, bool) {
	if o == nil || IsNil(o.Level) {
		return nil, false
	}
	return o.Level, true
}

// HasLevel returns a boolean if a field has been set.
func (o *OrderCampaign) HasLevel() bool {
	if o != nil && !IsNil(o.Level) {
		return true
	}

	return false
}

// SetLevel gets a reference to the given string and assigns it to the Level field.
func (o *OrderCampaign) SetLevel(v string) {
	o.Level = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *OrderCampaign) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCampaign) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *OrderCampaign) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *OrderCampaign) SetType(v string) {
	o.Type = &v
}

// GetUsageCount returns the UsageCount field value if set, zero value otherwise.
func (o *OrderCampaign) GetUsageCount() int64 {
	if o == nil || IsNil(o.UsageCount) {
		var ret int64
		return ret
	}
	return *o.UsageCount
}

// GetUsageCountOk returns a tuple with the UsageCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCampaign) GetUsageCountOk() (*int64, bool) {
	if o == nil || IsNil(o.UsageCount) {
		return nil, false
	}
	return o.UsageCount, true
}

// HasUsageCount returns a boolean if a field has been set.
func (o *OrderCampaign) HasUsageCount() bool {
	if o != nil && !IsNil(o.UsageCount) {
		return true
	}

	return false
}

// SetUsageCount gets a reference to the given int64 and assigns it to the UsageCount field.
func (o *OrderCampaign) SetUsageCount(v int64) {
	o.UsageCount = &v
}

// GetMexFundedRatio returns the MexFundedRatio field value if set, zero value otherwise.
func (o *OrderCampaign) GetMexFundedRatio() int32 {
	if o == nil || IsNil(o.MexFundedRatio) {
		var ret int32
		return ret
	}
	return *o.MexFundedRatio
}

// GetMexFundedRatioOk returns a tuple with the MexFundedRatio field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCampaign) GetMexFundedRatioOk() (*int32, bool) {
	if o == nil || IsNil(o.MexFundedRatio) {
		return nil, false
	}
	return o.MexFundedRatio, true
}

// HasMexFundedRatio returns a boolean if a field has been set.
func (o *OrderCampaign) HasMexFundedRatio() bool {
	if o != nil && !IsNil(o.MexFundedRatio) {
		return true
	}

	return false
}

// SetMexFundedRatio gets a reference to the given int32 and assigns it to the MexFundedRatio field.
func (o *OrderCampaign) SetMexFundedRatio(v int32) {
	o.MexFundedRatio = &v
}

// GetDeductedAmount returns the DeductedAmount field value if set, zero value otherwise.
func (o *OrderCampaign) GetDeductedAmount() int64 {
	if o == nil || IsNil(o.DeductedAmount) {
		var ret int64
		return ret
	}
	return *o.DeductedAmount
}

// GetDeductedAmountOk returns a tuple with the DeductedAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCampaign) GetDeductedAmountOk() (*int64, bool) {
	if o == nil || IsNil(o.DeductedAmount) {
		return nil, false
	}
	return o.DeductedAmount, true
}

// HasDeductedAmount returns a boolean if a field has been set.
func (o *OrderCampaign) HasDeductedAmount() bool {
	if o != nil && !IsNil(o.DeductedAmount) {
		return true
	}

	return false
}

// SetDeductedAmount gets a reference to the given int64 and assigns it to the DeductedAmount field.
func (o *OrderCampaign) SetDeductedAmount(v int64) {
	o.DeductedAmount = &v
}

// GetDeductedPart returns the DeductedPart field value if set, zero value otherwise.
func (o *OrderCampaign) GetDeductedPart() string {
	if o == nil || IsNil(o.DeductedPart) {
		var ret string
		return ret
	}
	return *o.DeductedPart
}

// GetDeductedPartOk returns a tuple with the DeductedPart field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCampaign) GetDeductedPartOk() (*string, bool) {
	if o == nil || IsNil(o.DeductedPart) {
		return nil, false
	}
	return o.DeductedPart, true
}

// HasDeductedPart returns a boolean if a field has been set.
func (o *OrderCampaign) HasDeductedPart() bool {
	if o != nil && !IsNil(o.DeductedPart) {
		return true
	}

	return false
}

// SetDeductedPart gets a reference to the given string and assigns it to the DeductedPart field.
func (o *OrderCampaign) SetDeductedPart(v string) {
	o.DeductedPart = &v
}

// GetAppliedItemIDs returns the AppliedItemIDs field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OrderCampaign) GetAppliedItemIDs() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.AppliedItemIDs
}

// GetAppliedItemIDsOk returns a tuple with the AppliedItemIDs field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OrderCampaign) GetAppliedItemIDsOk() ([]string, bool) {
	if o == nil || IsNil(o.AppliedItemIDs) {
		return nil, false
	}
	return o.AppliedItemIDs, true
}

// HasAppliedItemIDs returns a boolean if a field has been set.
func (o *OrderCampaign) HasAppliedItemIDs() bool {
	if o != nil && !IsNil(o.AppliedItemIDs) {
		return true
	}

	return false
}

// SetAppliedItemIDs gets a reference to the given []string and assigns it to the AppliedItemIDs field.
func (o *OrderCampaign) SetAppliedItemIDs(v []string) {
	o.AppliedItemIDs = v
}

// GetFreeItem returns the FreeItem field value if set, zero value otherwise.
func (o *OrderCampaign) GetFreeItem() OrderFreeItem {
	if o == nil || IsNil(o.FreeItem) {
		var ret OrderFreeItem
		return ret
	}
	return *o.FreeItem
}

// GetFreeItemOk returns a tuple with the FreeItem field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCampaign) GetFreeItemOk() (*OrderFreeItem, bool) {
	if o == nil || IsNil(o.FreeItem) {
		return nil, false
	}
	return o.FreeItem, true
}

// HasFreeItem returns a boolean if a field has been set.
func (o *OrderCampaign) HasFreeItem() bool {
	if o != nil && !IsNil(o.FreeItem) {
		return true
	}

	return false
}

// SetFreeItem gets a reference to the given OrderFreeItem and assigns it to the FreeItem field.
func (o *OrderCampaign) SetFreeItem(v OrderFreeItem) {
	o.FreeItem = &v
}

func (o OrderCampaign) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrderCampaign) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.CampaignNameForMex) {
		toSerialize["campaignNameForMex"] = o.CampaignNameForMex
	}
	if !IsNil(o.Level) {
		toSerialize["level"] = o.Level
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.UsageCount) {
		toSerialize["usageCount"] = o.UsageCount
	}
	if !IsNil(o.MexFundedRatio) {
		toSerialize["mexFundedRatio"] = o.MexFundedRatio
	}
	if !IsNil(o.DeductedAmount) {
		toSerialize["deductedAmount"] = o.DeductedAmount
	}
	if !IsNil(o.DeductedPart) {
		toSerialize["deductedPart"] = o.DeductedPart
	}
	if o.AppliedItemIDs != nil {
		toSerialize["appliedItemIDs"] = o.AppliedItemIDs
	}
	if !IsNil(o.FreeItem) {
		toSerialize["freeItem"] = o.FreeItem
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *OrderCampaign) UnmarshalJSON(data []byte) (err error) {
	varOrderCampaign := _OrderCampaign{}

	err = json.Unmarshal(data, &varOrderCampaign)

	if err != nil {
		return err
	}

	*o = OrderCampaign(varOrderCampaign)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "campaignNameForMex")
		delete(additionalProperties, "level")
		delete(additionalProperties, "type")
		delete(additionalProperties, "usageCount")
		delete(additionalProperties, "mexFundedRatio")
		delete(additionalProperties, "deductedAmount")
		delete(additionalProperties, "deductedPart")
		delete(additionalProperties, "appliedItemIDs")
		delete(additionalProperties, "freeItem")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableOrderCampaign struct {
	value *OrderCampaign
	isSet bool
}

func (v NullableOrderCampaign) Get() *OrderCampaign {
	return v.value
}

func (v *NullableOrderCampaign) Set(val *OrderCampaign) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderCampaign) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderCampaign) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderCampaign(val *OrderCampaign) *NullableOrderCampaign {
	return &NullableOrderCampaign{value: val, isSet: true}
}

func (v NullableOrderCampaign) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderCampaign) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


