// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
GrabFood

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.1.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package grabfood

import (
	"encoding/json"
)

// checks if the PosPriceDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PosPriceDetails{}

// PosPriceDetails A JSON object containing order's price in the minor unit format.
type PosPriceDetails struct {
	// Total item and modifier price  in minor units and tax-inclusive.
	Subtotal *int64 `json:"subtotal,omitempty"`
	// Total tax in the minor unit. ``` Formula Tax = total item/modifier tax 
	Tax *int64 `json:"tax,omitempty"`
	// Any additional fee charged by the merchant  in minor units and tax-inclusive, which is 100% paid out to the merchant. Eg. service charge
	MerchantChargeFeeInMin *int64 `json:"merchantChargeFeeInMin,omitempty"`
	// This field represents the reservation depositAmount, which is the amount paid upfront by the diner during the reservation process. It can be applied towards the final payment when the order is completed. It’s in minor units and tax-inclusive.
	DepositAmountInMin *int64 `json:"depositAmountInMin,omitempty"`
	// Offline discount that is provided to the diner in minor units and tax-inclusive.
	OfflinePOSDiscountInMin *int64 `json:"offlinePOSDiscountInMin,omitempty"`
	// The rounding amount in minor units.  ``` Round down should be in negative value Round up should be in positive value ``` 
	BillRoundingInMin *int64 `json:"billRoundingInMin,omitempty"`
	// The total bill value in minor units and tax-inclusive. ``` Formula:   eaterPayment =   + subtotal   + merchantChargeFeeInMin   - depositAmountInMin   - offlinePOSDiscountInMin 
	EaterPayment *int64 `json:"eaterPayment,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PosPriceDetails PosPriceDetails

// NewPosPriceDetails instantiates a new PosPriceDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPosPriceDetails() *PosPriceDetails {
	this := PosPriceDetails{}
	return &this
}

// NewPosPriceDetailsWithDefaults instantiates a new PosPriceDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPosPriceDetailsWithDefaults() *PosPriceDetails {
	this := PosPriceDetails{}
	return &this
}

// GetSubtotal returns the Subtotal field value if set, zero value otherwise.
func (o *PosPriceDetails) GetSubtotal() int64 {
	if o == nil || IsNil(o.Subtotal) {
		var ret int64
		return ret
	}
	return *o.Subtotal
}

// GetSubtotalOk returns a tuple with the Subtotal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PosPriceDetails) GetSubtotalOk() (*int64, bool) {
	if o == nil || IsNil(o.Subtotal) {
		return nil, false
	}
	return o.Subtotal, true
}

// HasSubtotal returns a boolean if a field has been set.
func (o *PosPriceDetails) HasSubtotal() bool {
	if o != nil && !IsNil(o.Subtotal) {
		return true
	}

	return false
}

// SetSubtotal gets a reference to the given int64 and assigns it to the Subtotal field.
func (o *PosPriceDetails) SetSubtotal(v int64) {
	o.Subtotal = &v
}

// GetTax returns the Tax field value if set, zero value otherwise.
func (o *PosPriceDetails) GetTax() int64 {
	if o == nil || IsNil(o.Tax) {
		var ret int64
		return ret
	}
	return *o.Tax
}

// GetTaxOk returns a tuple with the Tax field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PosPriceDetails) GetTaxOk() (*int64, bool) {
	if o == nil || IsNil(o.Tax) {
		return nil, false
	}
	return o.Tax, true
}

// HasTax returns a boolean if a field has been set.
func (o *PosPriceDetails) HasTax() bool {
	if o != nil && !IsNil(o.Tax) {
		return true
	}

	return false
}

// SetTax gets a reference to the given int64 and assigns it to the Tax field.
func (o *PosPriceDetails) SetTax(v int64) {
	o.Tax = &v
}

// GetMerchantChargeFeeInMin returns the MerchantChargeFeeInMin field value if set, zero value otherwise.
func (o *PosPriceDetails) GetMerchantChargeFeeInMin() int64 {
	if o == nil || IsNil(o.MerchantChargeFeeInMin) {
		var ret int64
		return ret
	}
	return *o.MerchantChargeFeeInMin
}

// GetMerchantChargeFeeInMinOk returns a tuple with the MerchantChargeFeeInMin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PosPriceDetails) GetMerchantChargeFeeInMinOk() (*int64, bool) {
	if o == nil || IsNil(o.MerchantChargeFeeInMin) {
		return nil, false
	}
	return o.MerchantChargeFeeInMin, true
}

// HasMerchantChargeFeeInMin returns a boolean if a field has been set.
func (o *PosPriceDetails) HasMerchantChargeFeeInMin() bool {
	if o != nil && !IsNil(o.MerchantChargeFeeInMin) {
		return true
	}

	return false
}

// SetMerchantChargeFeeInMin gets a reference to the given int64 and assigns it to the MerchantChargeFeeInMin field.
func (o *PosPriceDetails) SetMerchantChargeFeeInMin(v int64) {
	o.MerchantChargeFeeInMin = &v
}

// GetDepositAmountInMin returns the DepositAmountInMin field value if set, zero value otherwise.
func (o *PosPriceDetails) GetDepositAmountInMin() int64 {
	if o == nil || IsNil(o.DepositAmountInMin) {
		var ret int64
		return ret
	}
	return *o.DepositAmountInMin
}

// GetDepositAmountInMinOk returns a tuple with the DepositAmountInMin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PosPriceDetails) GetDepositAmountInMinOk() (*int64, bool) {
	if o == nil || IsNil(o.DepositAmountInMin) {
		return nil, false
	}
	return o.DepositAmountInMin, true
}

// HasDepositAmountInMin returns a boolean if a field has been set.
func (o *PosPriceDetails) HasDepositAmountInMin() bool {
	if o != nil && !IsNil(o.DepositAmountInMin) {
		return true
	}

	return false
}

// SetDepositAmountInMin gets a reference to the given int64 and assigns it to the DepositAmountInMin field.
func (o *PosPriceDetails) SetDepositAmountInMin(v int64) {
	o.DepositAmountInMin = &v
}

// GetOfflinePOSDiscountInMin returns the OfflinePOSDiscountInMin field value if set, zero value otherwise.
func (o *PosPriceDetails) GetOfflinePOSDiscountInMin() int64 {
	if o == nil || IsNil(o.OfflinePOSDiscountInMin) {
		var ret int64
		return ret
	}
	return *o.OfflinePOSDiscountInMin
}

// GetOfflinePOSDiscountInMinOk returns a tuple with the OfflinePOSDiscountInMin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PosPriceDetails) GetOfflinePOSDiscountInMinOk() (*int64, bool) {
	if o == nil || IsNil(o.OfflinePOSDiscountInMin) {
		return nil, false
	}
	return o.OfflinePOSDiscountInMin, true
}

// HasOfflinePOSDiscountInMin returns a boolean if a field has been set.
func (o *PosPriceDetails) HasOfflinePOSDiscountInMin() bool {
	if o != nil && !IsNil(o.OfflinePOSDiscountInMin) {
		return true
	}

	return false
}

// SetOfflinePOSDiscountInMin gets a reference to the given int64 and assigns it to the OfflinePOSDiscountInMin field.
func (o *PosPriceDetails) SetOfflinePOSDiscountInMin(v int64) {
	o.OfflinePOSDiscountInMin = &v
}

// GetBillRoundingInMin returns the BillRoundingInMin field value if set, zero value otherwise.
func (o *PosPriceDetails) GetBillRoundingInMin() int64 {
	if o == nil || IsNil(o.BillRoundingInMin) {
		var ret int64
		return ret
	}
	return *o.BillRoundingInMin
}

// GetBillRoundingInMinOk returns a tuple with the BillRoundingInMin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PosPriceDetails) GetBillRoundingInMinOk() (*int64, bool) {
	if o == nil || IsNil(o.BillRoundingInMin) {
		return nil, false
	}
	return o.BillRoundingInMin, true
}

// HasBillRoundingInMin returns a boolean if a field has been set.
func (o *PosPriceDetails) HasBillRoundingInMin() bool {
	if o != nil && !IsNil(o.BillRoundingInMin) {
		return true
	}

	return false
}

// SetBillRoundingInMin gets a reference to the given int64 and assigns it to the BillRoundingInMin field.
func (o *PosPriceDetails) SetBillRoundingInMin(v int64) {
	o.BillRoundingInMin = &v
}

// GetEaterPayment returns the EaterPayment field value if set, zero value otherwise.
func (o *PosPriceDetails) GetEaterPayment() int64 {
	if o == nil || IsNil(o.EaterPayment) {
		var ret int64
		return ret
	}
	return *o.EaterPayment
}

// GetEaterPaymentOk returns a tuple with the EaterPayment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PosPriceDetails) GetEaterPaymentOk() (*int64, bool) {
	if o == nil || IsNil(o.EaterPayment) {
		return nil, false
	}
	return o.EaterPayment, true
}

// HasEaterPayment returns a boolean if a field has been set.
func (o *PosPriceDetails) HasEaterPayment() bool {
	if o != nil && !IsNil(o.EaterPayment) {
		return true
	}

	return false
}

// SetEaterPayment gets a reference to the given int64 and assigns it to the EaterPayment field.
func (o *PosPriceDetails) SetEaterPayment(v int64) {
	o.EaterPayment = &v
}

func (o PosPriceDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PosPriceDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Subtotal) {
		toSerialize["subtotal"] = o.Subtotal
	}
	if !IsNil(o.Tax) {
		toSerialize["tax"] = o.Tax
	}
	if !IsNil(o.MerchantChargeFeeInMin) {
		toSerialize["merchantChargeFeeInMin"] = o.MerchantChargeFeeInMin
	}
	if !IsNil(o.DepositAmountInMin) {
		toSerialize["depositAmountInMin"] = o.DepositAmountInMin
	}
	if !IsNil(o.OfflinePOSDiscountInMin) {
		toSerialize["offlinePOSDiscountInMin"] = o.OfflinePOSDiscountInMin
	}
	if !IsNil(o.BillRoundingInMin) {
		toSerialize["billRoundingInMin"] = o.BillRoundingInMin
	}
	if !IsNil(o.EaterPayment) {
		toSerialize["eaterPayment"] = o.EaterPayment
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PosPriceDetails) UnmarshalJSON(data []byte) (err error) {
	varPosPriceDetails := _PosPriceDetails{}

	err = json.Unmarshal(data, &varPosPriceDetails)

	if err != nil {
		return err
	}

	*o = PosPriceDetails(varPosPriceDetails)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "subtotal")
		delete(additionalProperties, "tax")
		delete(additionalProperties, "merchantChargeFeeInMin")
		delete(additionalProperties, "depositAmountInMin")
		delete(additionalProperties, "offlinePOSDiscountInMin")
		delete(additionalProperties, "billRoundingInMin")
		delete(additionalProperties, "eaterPayment")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePosPriceDetails struct {
	value *PosPriceDetails
	isSet bool
}

func (v NullablePosPriceDetails) Get() *PosPriceDetails {
	return v.value
}

func (v *NullablePosPriceDetails) Set(val *PosPriceDetails) {
	v.value = val
	v.isSet = true
}

func (v NullablePosPriceDetails) IsSet() bool {
	return v.isSet
}

func (v *NullablePosPriceDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePosPriceDetails(val *PosPriceDetails) *NullablePosPriceDetails {
	return &NullablePosPriceDetails{value: val, isSet: true}
}

func (v NullablePosPriceDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePosPriceDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


