// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
GrabFood

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.1.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package grabfood

import (
	"encoding/json"
	"fmt"
)

// checks if the UpdateSpecialHourRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateSpecialHourRequest{}

// UpdateSpecialHourRequest Object contains store special hours.
type UpdateSpecialHourRequest struct {
	// An array of objects contain store special hours. Max. 3 array elements.
	SpecialOpeningHours []SpecialOpeningHour `json:"specialOpeningHours"`
	AdditionalProperties map[string]interface{}
}

type _UpdateSpecialHourRequest UpdateSpecialHourRequest

// NewUpdateSpecialHourRequest instantiates a new UpdateSpecialHourRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateSpecialHourRequest(specialOpeningHours []SpecialOpeningHour) *UpdateSpecialHourRequest {
	this := UpdateSpecialHourRequest{}
	this.SpecialOpeningHours = specialOpeningHours
	return &this
}

// NewUpdateSpecialHourRequestWithDefaults instantiates a new UpdateSpecialHourRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateSpecialHourRequestWithDefaults() *UpdateSpecialHourRequest {
	this := UpdateSpecialHourRequest{}
	return &this
}

// GetSpecialOpeningHours returns the SpecialOpeningHours field value
func (o *UpdateSpecialHourRequest) GetSpecialOpeningHours() []SpecialOpeningHour {
	if o == nil {
		var ret []SpecialOpeningHour
		return ret
	}

	return o.SpecialOpeningHours
}

// GetSpecialOpeningHoursOk returns a tuple with the SpecialOpeningHours field value
// and a boolean to check if the value has been set.
func (o *UpdateSpecialHourRequest) GetSpecialOpeningHoursOk() ([]SpecialOpeningHour, bool) {
	if o == nil {
		return nil, false
	}
	return o.SpecialOpeningHours, true
}

// SetSpecialOpeningHours sets field value
func (o *UpdateSpecialHourRequest) SetSpecialOpeningHours(v []SpecialOpeningHour) {
	o.SpecialOpeningHours = v
}

func (o UpdateSpecialHourRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateSpecialHourRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["specialOpeningHours"] = o.SpecialOpeningHours

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateSpecialHourRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"specialOpeningHours",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateSpecialHourRequest := _UpdateSpecialHourRequest{}

	err = json.Unmarshal(data, &varUpdateSpecialHourRequest)

	if err != nil {
		return err
	}

	*o = UpdateSpecialHourRequest(varUpdateSpecialHourRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "specialOpeningHours")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateSpecialHourRequest struct {
	value *UpdateSpecialHourRequest
	isSet bool
}

func (v NullableUpdateSpecialHourRequest) Get() *UpdateSpecialHourRequest {
	return v.value
}

func (v *NullableUpdateSpecialHourRequest) Set(val *UpdateSpecialHourRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateSpecialHourRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateSpecialHourRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateSpecialHourRequest(val *UpdateSpecialHourRequest) *NullableUpdateSpecialHourRequest {
	return &NullableUpdateSpecialHourRequest{value: val, isSet: true}
}

func (v NullableUpdateSpecialHourRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateSpecialHourRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


